### ISSUE TITLE
Thanks and a Question

### ISSUE THREAD

**Issue by scotthardwick** [smdvdsn/hauntedpi#1]
Hello smdvdsn,

This isn't really an issue report, instead a great thanks for sharing this code.  My pirate themed Halloween home setup is going to be awesome thanks to you!

One question... When you are running the software are you running it via SSH or running it headless on the pi?  Running via SSH I have no problems. Running headless, I get is a loud squeal out of the 3.5 connected speakers.  

Happy Haunting,
Scott

**Comment by scotthardwick** [comment]
Just following up in case anyone else hits my problem. It was pathing ;-)  Ensuring you have the full path to your sound files makes things placed in crontab @reboot much happier ;-)

**Comment by smdvdsn** [comment]
Hi scotthardwick,

I'm glad you managed to get it going. Sorry I didn't reply to your earlier question. For some reason I didn't get a notification from GitHub, so I totally missed it.

Happy Haunting to you as well
Scott
